# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Assemblyai < Formula
  desc "A quick and easy way to test assemblyAI's transcription features on your terminal"
  homepage "https://www.assemblyai.com/"
  version "0.20"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/AssemblyAI/assemblyai-cli/releases/download/v0.20/assemblyai_0.20_darwin_arm64.tar.gz"
      sha256 "902bc8f913cbbd4c935cf32e3b3a3073164e7b66d1db9b3fbb81048add49a2d1"

      def install
        bin.install "assemblyai"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/AssemblyAI/assemblyai-cli/releases/download/v0.20/assemblyai_0.20_darwin_amd64.tar.gz"
      sha256 "9b802199f4681d2a7a5d538cf9ba87b54ff2aacf253c870fe66f152ddffe4836"

      def install
        bin.install "assemblyai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/AssemblyAI/assemblyai-cli/releases/download/v0.20/assemblyai_0.20_linux_amd64.tar.gz"
      sha256 "361d3775d2dacac07d2b27f29722ca4ec69a8c3268ddb0e0e18fcbb2c6bf2e83"

      def install
        bin.install "assemblyai"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/AssemblyAI/assemblyai-cli/releases/download/v0.20/assemblyai_0.20_linux_armv6.tar.gz"
      sha256 "0bfeb8ef03f02c260e66a6e84a9f5f3ea81b89106221394d70c21fac9978b9c9"

      def install
        bin.install "assemblyai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AssemblyAI/assemblyai-cli/releases/download/v0.20/assemblyai_0.20_linux_arm64.tar.gz"
      sha256 "c8c8d3e763e0932f7c61e2a4d58106b1a5407f36ad48939038eb9dd45e5f2c39"

      def install
        bin.install "assemblyai"
      end
    end
  end

  test do
    output = shell_output("#{bin}/assemblyai-cli config 1234567890")
    expected = "Invalid token. Try again, and if the problem persists, contact support at support@assemblyai.com"
    assert_match expected, output

    output = shell_output("#{bin}/assemblyai-cli transcribe 1234567890")
    assert_match "You must login first. Run `assemblyai config <token>`\n", output

    output = shell_output("#{bin}/assemblyai-cli get 1234567890")
    assert_match "You must login first. Run `assemblyai config <token>`\n", output
  end
end
