# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Assemblyai < Formula
  desc "A quick and easy way to test assemblyAI's transcription features on your terminal"
  homepage "https://www.assemblyai.com/"
  version "0.9"
  license "Apache 2.0"

  on_macos do
    url "https://github.com/AssemblyAI/assemblyai-cli/releases/download/v0.9/assemblyai-cli_0.9_darwin_all.tar.gz"
    sha256 "afefdde4c9e30116b060cf942bdd10074865ad7278fc456c4caf24328554fa31"

    def install
      bin.install "assemblyai-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AssemblyAI/assemblyai-cli/releases/download/v0.9/assemblyai-cli_0.9_linux_arm64.tar.gz"
      sha256 "f470665fc245c03a5a7b483ba745fc39aae84a9502c4ab6513f0e6c565a4d094"

      def install
        bin.install "assemblyai"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/AssemblyAI/assemblyai-cli/releases/download/v0.9/assemblyai-cli_0.9_linux_amd64.tar.gz"
      sha256 "6fd10accca80f66ba4cd20bda9701cd738ec07a50853f95d7a2d2894c01c1c7e"

      def install
        bin.install "assemblyai"
      end
    end
  end
end
