# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AssemblyaiCli < Formula
  desc ""
  homepage "https://www.assemblyai.com/"
  version "0.6"

  on_macos do
    url "https://github.com/AssemblyAI/assemblyai-cli/releases/download/v0.6/assemblyai-cli_0.6_darwin_all.tar.gz"
    sha256 "7e0065fc1ae328e28e191100a1be5507a362afecf7ea84d8cf43a4b61d56c4ed"

    def install
      bin.install "assemblyai-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AssemblyAI/assemblyai-cli/releases/download/v0.6/assemblyai-cli_0.6_linux_arm64.tar.gz"
      sha256 "e43240c80f1ce4307ebe9b74df63788d6e942b81dd2f942c8534e47f5fc918bb"

      def install
        bin.install "assemblyai-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/AssemblyAI/assemblyai-cli/releases/download/v0.6/assemblyai-cli_0.6_linux_amd64.tar.gz"
      sha256 "93a7e382b3f24e7be04936f5f46b1c7856d4d0bb5566ebaab857cd2c81485992"

      def install
        bin.install "assemblyai-cli"
      end
    end
  end
end
