# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AssemblyaiCli < Formula
  desc "A quick and easy way to test assemblyAI's transcription features on your terminal"
  homepage "https://www.assemblyai.com/"
  version "0.7"
  license "Apache 2.0"

  on_macos do
    url "https://github.com/AssemblyAI/assemblyai-cli/releases/download/v0.7/assemblyai-cli_0.7_darwin_all.tar.gz"
    sha256 "3f3291519de378b63d200c634a0a8655e80e2f71f733c16c77cd76034b088e19"

    def install
      bin.install "assemblyai-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AssemblyAI/assemblyai-cli/releases/download/v0.7/assemblyai-cli_0.7_linux_arm64.tar.gz"
      sha256 "98f179173349640fc1ed448b903c373d57d257208768587588fbfd49c39e657f"

      def install
        bin.install "assemblyai-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/AssemblyAI/assemblyai-cli/releases/download/v0.7/assemblyai-cli_0.7_linux_amd64.tar.gz"
      sha256 "974a83475a61eead63cab7e08716bf0b4a2d69261ba7d31aa69847c7af06b7ca"

      def install
        bin.install "assemblyai-cli"
      end
    end
  end
end
