# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Assemblyai < Formula
  desc "A quick and easy way to test assemblyAI's transcription features on your terminal"
  homepage "https://www.assemblyai.com/"
  version "1.10.2"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AssemblyAI/assemblyai-cli/releases/download/v1.10.2/assemblyai_1.10.2_darwin_amd64.tar.gz"
      sha256 "2d377ac23b662fee4eefe803f7c9c780b59acbd08cf7960122f71fe151ae5ec5"

      def install
        bin.install "assemblyai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AssemblyAI/assemblyai-cli/releases/download/v1.10.2/assemblyai_1.10.2_darwin_arm64.tar.gz"
      sha256 "79d26cd5be623bcd720cbb47eb1480469123664c51cba2e3ae21a910d4fd04c3"

      def install
        bin.install "assemblyai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AssemblyAI/assemblyai-cli/releases/download/v1.10.2/assemblyai_1.10.2_linux_arm64.tar.gz"
      sha256 "0044a032b5c59f551ebde9ce1fc76dcf4ee8e1f078bd1e2be847f650ef09cdc7"

      def install
        bin.install "assemblyai"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/AssemblyAI/assemblyai-cli/releases/download/v1.10.2/assemblyai_1.10.2_linux_amd64.tar.gz"
      sha256 "0fa06f59b70ce9da86124cd31f99c8ce57f3ef7347fcd770e35860ebd223ac58"

      def install
        bin.install "assemblyai"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/AssemblyAI/assemblyai-cli/releases/download/v1.10.2/assemblyai_1.10.2_linux_armv6.tar.gz"
      sha256 "64f885bb3724b4019203a1aabe0356836caf68d3a7e6d9e459b026013efdf8dc"

      def install
        bin.install "assemblyai"
      end
    end
  end

  test do
    output = shell_output("#{bin}/assemblyai config 1234567890")
    expected = "Invalid token. Try again, and if the problem persists, contact support at support@assemblyai.com"
    assert_match expected, output

    output = shell_output("#{bin}/assemblyai transcribe 1234567890")
    assert_match "You must login first. Run `assemblyai config <token>`\n", output

    output = shell_output("#{bin}/assemblyai get 1234567890")
    assert_match "You must login first. Run `assemblyai config <token>`\n", output
  end
end
